### PR TITLE
Search Functionality and Separate Header

### PR DESCRIPTION
**Pull request by Maxgriff**
This pull request adds the following features:
- Popup on search page now has filters that can be used
- Search bar now can take user input
- Search bar links back to search page when user presses "Enter"
- Search page now takes user input as a parameter
- The header component without a search bar has been added
- All pages (except edit profile page) now contain some version of the header

### CODE REVIEW

**Comment by andresrivas20** [comment]
Look good man, I'll add the header to the edit profile page

**Comment by ejmercier** [comment]
Looks great. Only thing I can think of (i know its nitpicky) is do we care that the search results and filters are off center?
image
could just be my display.

**Comment by andresrivas20** [comment]
> Looks great. Only thing I can think of (i know its nitpicky) is do we care that the search results and filters are off center? image could just be my display.

I think it's fine to check in for now and then make that fix in a following PR

**Comment by andresrivas20** [comment]
I think it might be a good idea to center those components. maybe in this PR or in a following PR

**Comment by Maxgriff** [comment]
> Looks great. Only thing I can think of (i know its nitpicky) is do we care that the search results and filters are off center?
> image
> could just be my display.
> 
> 

I can easily fix this.  I think it's probably because I've been testing on my monitor and coding on my laptop.  I'll make it adjust based on screen size (small, medium, large)

**Comment by ejmercier** [comment]
Sounds good. You can merge whenever you are ready then.

**Review by ejmercier — APPROVED** [review]

**Pull request merged**
