### PR TITLE
Connecting Feeds

### PR DESCRIPTION
**Pull request by ejmercier**
This PR is for connecting the Feeds with the backend and some small minor UI changes I made along the way.

My changes related to the feed are as follows:
- Created the /feed , /feed/athlete , and /feed/sponsor routes to allow users to view all the posts, just athlete posts, or just sponsor posts
- Linked the Feed, Athlete, and Sponsor buttons on the header and homepage to navigate to the respective feeds
- Added a background image on the feed to fill the whitespace

My changes related to UI are as follows:
- Added a border that appears on the header when users hover over an option they want to select (this is for all options)
- Added navigation from create athlete profile button on the homepage to link to the signup page
- Fixed default text that was duplicate on the "Post to Feed" section of the homepage

### CODE REVIEW

**Review by Kevin-Daniel — COMMENTED** [review]
Tried changes locally, everything works good. Only feedback I have is that perhaps conditionally render "Create Athlete Profile" button on the homepage depending on whether the user is logged in or not. Perhaps not displaying the button completely if the user is already logged in, or change it to "View Profile" or "Edit Profile" if the user is already logged in.

**Comment by ejmercier** [comment]
The View Profile button conditional rendering is fixed in 34d96468eda0ac63dae959d59c7b6e1f86464470 😃

**Review by andresrivas20 — DISMISSED** [review]
Great work!

**Review by Kevin-Daniel — APPROVED** [review]
Everything works great, fantastic work! Approved.

**Pull request merged**
