### PR TITLE
Delete Posts & Change Profile Picture

### PR DESCRIPTION
**Pull request by andresrivas20**
Additions:

-delete posts, all posts are deleted from the front end and backend
-change profile picture. user can change profile picture and it is stored in the database

### CODE REVIEW

**Review by Kevin-Daniel — DISMISSED** [review]
Everything works on my end, great work. Approved. Just resolve the merge conflicts and it should be good for merging.

**Review by Kevin-Daniel — COMMENTED** [review]
Tried it out again and for some reason some things appear broken to me. For example when I click on a post on a user's profile, a lot of the elements are undefined/don't appear. For example: 
image

I believe the problem is in Post.js where the properties we are trying to access don't match the name in the SQL database.
For example, I believe it should be `post.UserName`, `post.Instagram`, etc.
image

There may be other places that need fixing like that as well. After looking into it, it seems like this was caused by some of the changes in the last pull request we merged.

**Comment by andresrivas20** [comment]
@Kevin-Daniel yes that was the issue. the last PR changes the naming conventions and was not in accordance with the database. The fetch route in the server was renaming those properties but I fixed the queries to not do that. All should work now

**Review by Kevin-Daniel — APPROVED** [review]
Tested it out, its all good. Thanks for fixing that. Approved.

**Pull request merged**
